### ISSUE TITLE
Nightly - Pros Depends on Removed Feature "stdsimd"

### ISSUE THREAD

**Issue by microcrit** [pros-rs/pros-rs#94]
## Bug Description
Installing Pros-RS 0.6.0 on latest Rust Nightly results in "unknown feature `stdsimd`."   
This feature [was removed](https://users.rust-lang.org/t/error-e0635-unknown-feature-stdsimd/106445/2) in [recent Nightly updates](https://github.com/rust-lang/rust/commit/ea37e8091fe87ae0a7e204c034e7d55061e56790).

## Code to reproduce
```
git clone https://github.com/pros-rs/pros-template-rust.git
cd pros-template-rust
cargo +nightly install --path .
```

## Expected vs. actual behavior
The library should properly install all dependencies without errors and without the reliance on recently-removed features.

## Additional information
- Operating system (Linux/macOS/Windows): Windows
- pros-rs version (see `Cargo.toml`): 1.78.0 Nightly (Latest)
- Rust version (see `rustc --version`): rustc 1.78.0-nightly (0ecbd0605 2024-02-25)
- Priority this issue should have (low/med/high): low
- I would be willing to implement a fix for this issue.

**Comment by Gavin-Niederman** [comment]
I believe that this is fixed in an already created PR.

**Comment by Gavin-Niederman** [comment]
The PR I was thinking of has already been merged. Are you sure that this is still an issue?

**Comment by microcrit** [comment]
I've also tested this on 0.7.0 and it looks like this is still an issue in nightly.

**Comment by doinkythederp** [comment]
Can you try on the latest git release?

**Comment by microcrit** [comment]
im not smart nvm fixed
